packages:
  - apps/*
  - packages/*
catalog:
  next: 15.3.2
  eslint-config-next: 15.3.2
  '@next/mdx': 15.3.2
  '@next/eslint-plugin-next': 15.3.2
  react: ^19.1
  react-dom: ^19.1
  '@types/react': ^19
  '@types/react-dom': ^19
  tailwindcss: ^4.1.7
  '@tailwindcss/postcss': ^4.1.7
  '@tailwindcss/vite': ^4.1.7
  eslint: ^9
  '@eslint/eslintrc': ^3
  typescript: ^5
  '@types/node': ^22
onlyBuiltDependencies:
  - '@swc/core'
  - '@tailwindcss/oxide'
  - better-sqlite3
  - core-js-pure
  - esbuild
  - sharp
  - unrs-resolver
